const QUESTION_POOL = [
  { type: 'multiple', question: 'Türkiye\'nin başkenti neresidir?', options: ['İstanbul', 'İzmir', 'Ankara', 'Bursa'], answer: 2 },
  { type: 'multiple', question: '7 x 8 işleminin sonucu nedir?', options: ['54', '56', '58', '64'], answer: 1 },
  { type: 'multiple', question: 'En büyük okyanus hangisidir?', options: ['Atlas', 'Hint', 'Arktik', 'Pasifik'], answer: 3 },
  { type: 'multiple', question: 'Hangi hayvan memelidir?', options: ['Kaplumbağa', 'Yunus', 'Timsah', 'Martı'], answer: 1 },
  { type: 'multiple', question: 'Günde kaç saat vardır?', options: ['24', '12', '48', '36'], answer: 0 },
  { type: 'multiple', question: 'En uzun nehir hangisidir?', options: ['Amazon', 'Nil', 'Tuna', 'Mississippi'], answer: 1 },
  { type: 'multiple', question: 'Mars gezegenine verilen diğer ad nedir?', options: ['Mavi Gezegen', 'Kırmızı Gezegen', 'Güneşin Çocuğu', 'Taşlı Gezegen'], answer: 1 },
  { type: 'multiple', question: 'En küçük asal sayı kaçtır?', options: ['0', '1', '2', '3'], answer: 2 },
  { type: 'multiple', question: '"Elma" kelimesinin eş anlamlısı hangisidir?', options: ['Meyve', 'Sebze', 'Yoktur', 'Armut'], answer: 2 },
  { type: 'multiple', question: 'Atatürk hangi tarihte doğmuştur?', options: ['1881', '1919', '1923', '1938'], answer: 0 },
  { type: 'multiple', question: '1000 ÷ 5 sonucu nedir?', options: ['150', '200', '250', '300'], answer: 1 },
  { type: 'multiple', question: 'İstanbul Boğazı hangi iki kıtayı ayırır?', options: ['Avrupa – Afrika', 'Asya – Amerika', 'Avrupa – Asya', 'Afrika – Antarktika'], answer: 2 },
  { type: 'multiple', question: 'Güneş sisteminde kaç gezegen vardır?', options: ['7', '8', '9', '10'], answer: 1 },
  { type: 'multiple', question: 'DNA nedir?', options: ['Kas hücresi', 'Protein', 'Genetik bilgi taşıyan molekül', 'Hormon'], answer: 2 },
  { type: 'multiple', question: '1 yıl kaç gündür?', options: ['364', '365', '366', '367'], answer: 1 },
  { type: 'multiple', question: 'Mavi renk hangi duyguyu temsil eder?', options: ['Korku', 'Sakinlik', 'Sinir', 'Heyecan'], answer: 1 },
  { type: 'multiple', question: 'En çok konuşulan dil hangisidir?', options: ['İngilizce', 'Arapça', 'Çince', 'Hintçe'], answer: 2 },
  { type: 'multiple', question: 'En hızlı kara hayvanı hangisidir?', options: ['Kaplan', 'Ceylan', 'Aslan', 'Çita'], answer: 3 },
  { type: 'multiple', question: 'Fotosentez hangi yapı ile yapılır?', options: ['Mitokondri', 'Kloroplast', 'Ribozom', 'Çekirdek'], answer: 1 },
  { type: 'multiple', question: 'Türkiye hangi kıtalarda yer alır?', options: ['Avrupa – Asya', 'Afrika – Avrupa', 'Asya – Afrika', 'Amerika – Avrupa'], answer: 0 },
  { type: 'multiple', question: 'Güneş doğudan mı batar?', options: ['Evet', 'Hayır'], answer: 1 },
  { type: 'multiple', question: 'En uzun organımız hangisidir?', options: ['Kalp', 'Akciğer', 'Deri', 'Karaciğer'], answer: 2 },
  { type: 'multiple', question: '3, 6, 9, 12, ? → Sıradaki sayı?', options: ['14', '15', '16', '18'], answer: 1 },
  { type: 'multiple', question: 'En çok kullanılan sosyal medya uygulaması hangisidir? (2025 tahmini)', options: ['Facebook', 'Instagram', 'TikTok', 'X (Twitter)'], answer: 2 },
  { type: 'multiple', question: 'Çay genelde nasıl içilir?', options: ['Sıcak', 'Soğuk', 'Donmuş', 'Buharlı'], answer: 0 },
  { type: 'multiple', question: 'En popüler işletim sistemi hangisidir?', options: ['Linux', 'MacOS', 'Windows', 'Ubuntu'], answer: 2 },
  { type: 'multiple', question: 'Beş duyu organımızdan biri aşağıdakilerden hangisidir?', options: ['Karaciğer', 'Cilt', 'Burun', 'Mide'], answer: 2 },
  { type: 'multiple', question: 'Tersine yazılmış kelime: "kabaK" → Düz hali?', options: ['Kabak', 'Kakab', 'Kabka', 'Kkaba'], answer: 0 },
  { type: 'multiple', question: 'En çok bilinen mesleklerden biri nedir?', options: ['Bilimci', 'Yüzücü', 'Öğretmen', 'Besteci'], answer: 2 },
  { type: 'multiple', question: '15 + 24 – 10 = ?', options: ['29', '31', '32', '33'], answer: 0 },
  { type: 'multiple', question: '81 sayısı hangi sayının karesidir?', options: ['7', '8', '9', '10'], answer: 2 },
  { type: 'multiple', question: 'Dünya\'nın uydusu hangisidir?', options: ['Venüs', 'Güneş', 'Mars', 'Ay'], answer: 3 },
  { type: 'multiple', question: '100 / 4 işleminin sonucu nedir?', options: ['20', '25', '30', '40'], answer: 1 },
  { type: 'multiple', question: 'Hangi ülke Avrupa\'dadır?', options: ['Japonya', 'Türkiye', 'Brezilya', 'Mısır'], answer: 1 },
  { type: 'multiple', question: '1 metre kaç santimetredir?', options: ['10', '100', '1000', '10000'], answer: 1 },
  { type: 'multiple', question: 'En yaygın kullanılan arama motoru nedir?', options: ['Bing', 'Yandex', 'Google', 'Yahoo'], answer: 2 },
  { type: 'multiple', question: 'Kış mevsiminde hangisi olur?', options: ['Ağaçlar çiçek açar', 'Kar yağar', 'Güneş batmaz', 'Sıcaklık artar'], answer: 1 },
  { type: 'multiple', question: 'Türkiye\'nin en kalabalık şehri hangisidir?', options: ['Ankara', 'İzmir', 'İstanbul', 'Bursa'], answer: 2 },
  { type: 'multiple', question: '"Photoshop" hangi alanda kullanılır?', options: ['Yazılım', 'Resim düzenleme', 'Müzik yapımı', 'Muhasebe'], answer: 1 },
  { type: 'multiple', question: '5² işlemi kaçtır?', options: ['10', '20', '25', '30'], answer: 2 },
  { type: 'multiple', question: 'Türkiye\'nin para birimi nedir?', options: ['Dolar', 'Euro', 'TL', 'Yen'], answer: 2 },
  { type: 'multiple', question: 'Kan grubunu belirleyen sistem hangisidir?', options: ['ABO', 'RNA', 'XYZ', 'HDL'], answer: 0 },
  { type: 'multiple', question: 'Hangi sayı çift sayıdır?', options: ['13', '21', '28', '35'], answer: 2 },
  { type: 'multiple', question: 'Bir yılda kaç ay vardır?', options: ['10', '11', '12', '13'], answer: 2 },
  { type: 'multiple', question: '60 + 15 – 30 işleminin sonucu nedir?', options: ['45', '40', '30', '50'], answer: 0 },
  { type: 'multiple', question: 'Gökkuşağında kaç renk vardır?', options: ['5', '6', '7', '8'], answer: 2 },
  { type: 'multiple', question: '"Ctrl + C" bilgisayarda hangi işlevi görür?', options: ['Kapat', 'Kes', 'Kopyala', 'Yapıştır'], answer: 2 },
  { type: 'multiple', question: 'En yaygın sosyal medya platformu hangisidir?', options: ['Reddit', 'Instagram', 'TikTok', 'Tumblr'], answer: 2 },
  { type: 'multiple', question: 'Türkiye\'nin en uzun nehri hangisidir?', options: ['Fırat', 'Dicle', 'Kızılırmak', 'Meriç'], answer: 0 },
  { type: 'multiple', question: '"Kavanoz" kelimesinin zıt anlamlısı nedir?', options: ['Kap', 'Şişe', 'Boşluk', 'Yoktur'], answer: 3 },
  { type: 'multiple', question: 'Sudoku hangi tür oyundur?', options: ['Zeka', 'Strateji', 'Refleks', 'Aksiyon'], answer: 0 },
  { type: 'multiple', question: 'Bir karenin kaç kenarı vardır?', options: ['3', '4', '5', '6'], answer: 1 },
  { type: 'multiple', question: 'Hangi gezegen halkalı yapıya sahiptir?', options: ['Mars', 'Dünya', 'Satürn', 'Merkür'], answer: 2 },
  { type: 'multiple', question: 'Türkiye\'nin en doğusundaki il hangisidir?', options: ['Edirne', 'Artvin', 'Iğdır', 'Gaziantep'], answer: 2 },
  { type: 'multiple', question: '"E=mc²" formülü kime aittir?', options: ['Newton', 'Einstein', 'Tesla', 'Galileo'], answer: 1 },
  { type: 'multiple', question: 'Aşağıdaki renklerden hangisi sıcak renktir?', options: ['Mavi', 'Yeşil', 'Kırmızı', 'Mor'], answer: 2 },
  { type: 'multiple', question: 'En büyük asal sayı aşağıdakilerden hangisidir?', options: ['97', '90', '88', '99'], answer: 0 },
  { type: 'multiple', question: 'Günümüzde yaygın kullanılan dosya sıkıştırma uzantısı hangisidir?', options: ['.doc', '.zip', '.exe', '.avi'], answer: 1 },
  { type: 'multiple', question: '1 kilometre kaç metredir?', options: ['100', '1000', '10', '10.000'], answer: 1 },
  { type: 'multiple', question: 'En küçük pozitif çift sayı nedir?', options: ['0', '1', '2', '4'], answer: 2 },
  { type: 'multiple', question: 'Pi sayısı yaklaşık olarak kaçtır?', options: ['2.14', '3.14', '4.14', '5.14'], answer: 1 },
  { type: 'multiple', question: 'En büyük kara hayvanı hangisidir?', options: ['Fil', 'Zürafa', 'Gergedan', 'Ayı'], answer: 0 },
  { type: 'multiple', question: 'Bir saat kaç dakikadır?', options: ['60', '100', '30', '90'], answer: 0 },
  { type: 'multiple', question: 'Hangi harf Türk alfabesinde yoktur?', options: ['Ç', 'Q', 'Ş', 'Ğ'], answer: 1 },
  { type: 'multiple', question: 'DNA\'nın açılımı nedir?', options: ['Dinamik Nükleotid Ağı', 'Deoksiribonükleik Asit', 'Dijital Nöron Alanı', 'Difüzyon Nükleer Akımı'], answer: 1 },
  { type: 'multiple', question: 'Hangi element gaz halindedir?', options: ['Oksijen', 'Demir', 'Gümüş', 'Bakır'], answer: 0 },
  { type: 'multiple', question: 'Günümüzde en yaygın kullanılan mesajlaşma uygulaması hangisidir?', options: ['Signal', 'WhatsApp', 'Telegram', 'Discord'], answer: 1 },
  { type: 'multiple', question: '45 sayısı 3 ile bölünebilir mi?', options: ['Hayır', 'Evet', 'Bazen', 'Emin değilim'], answer: 1 },
  { type: 'multiple', question: 'Hangi ülkenin bayrağı kırmızı-beyazdır?', options: ['Kanada', 'Fransa', 'Almanya', 'Hindistan'], answer: 0 },
  { type: 'multiple', question: 'Hangi gezegen Güneş\'e en yakındır?', options: ['Venüs', 'Mars', 'Merkür', 'Uranüs'], answer: 2 },
  { type: 'multiple', question: 'Kare prizmanın kaç yüzü vardır?', options: ['4', '5', '6', '8'], answer: 2 },
  { type: 'multiple', question: 'Bir üçgenin iç açıları toplamı kaç derecedir?', options: ['180', '360', '90', '270'], answer: 0 },
  { type: 'multiple', question: 'Çarpım tablosunda 6x7 kaçtır?', options: ['42', '36', '48', '40'], answer: 0 },
  { type: 'multiple', question: 'Bir bilgisayarda RAM ne işe yarar?', options: ['Sabit depolama', 'Ses işleme', 'Geçici bellek', 'İnternet bağlantısı'], answer: 2 },
  { type: 'multiple', question: 'Türkiye\'nin ilk başkenti neresidir?', options: ['İstanbul', 'Ankara', 'İzmir', 'Bursa'], answer: 3 },
  { type: 'multiple', question: 'Hangisi duyusal bir organ değildir?', options: ['Kulak', 'Dil', 'Burun', 'Mide'], answer: 3 },
  { type: 'multiple', question: 'Hangi gezegenin halkası vardır?', options: ['Dünya', 'Mars', 'Satürn', 'Venüs'], answer: 2 },
  { type: 'multiple', question: 'Bir haftada kaç gün vardır?', options: ['6', '7', '8', '9'], answer: 1 },
  { type: 'multiple', question: 'Karbon dioksit hangi sembolle gösterilir?', options: ['CO', 'CO₂', 'C₂O', 'C₂O₂'], answer: 1 },
  { type: 'multiple', question: 'İlk çağlarda kullanılan yazı türü nedir?', options: ['Latin', 'Hiyeroglif', 'Kiril', 'Arap'], answer: 1 },
  { type: 'multiple', question: 'Hangi araç su üstünde hareket eder?', options: ['Araba', 'Uçak', 'Gemi', 'Tren'], answer: 2 },
  { type: 'multiple', question: '"Photosynthesis" ne anlama gelir?', options: ['Nefes alma', 'Terleme', 'Fotosentez', 'Solunum'], answer: 2 },
  { type: 'multiple', question: 'Hangi işlem sonucu çift sayıdır?', options: ['3 + 3', '5 + 1', '4 + 2', '5 + 5'], answer: 2 },
  { type: 'multiple', question: '1 saat 45 dakika kaç dakikadır?', options: ['105', '100', '90', '115'], answer: 0 },
  { type: 'multiple', question: 'En küçük asal sayı nedir?', options: ['0', '1', '2', '3'], answer: 2 },
  { type: 'multiple', question: 'Güneş hangi sınıfa girer?', options: ['Yıldız', 'Gezegen', 'Uydu', 'Asteroit'], answer: 0 },
  { type: 'multiple', question: '"Ctrl + Z" tuş kombinasyonu ne işe yarar?', options: ['Yapıştır', 'Kopyala', 'Geri al', 'Yeniden başlat'], answer: 2 },
  { type: 'multiple', question: 'Suyun donma noktası kaç °C\'dir?', options: ['0', '10', '-10', '100'], answer: 0 },
  { type: 'multiple', question: 'Türkiye\'de resmi dil nedir?', options: ['İngilizce', 'Almanca', 'Türkçe', 'Arapça'], answer: 2 },
  { type: 'multiple', question: 'Hangi gezegen Güneş Sistemi\'nin en büyüğüdür?', options: ['Uranüs', 'Neptün', 'Jüpiter', 'Mars'], answer: 2 },
  { type: 'multiple', question: 'Hangi hayvan uçamaz?', options: ['Güvercin', 'Kartal', 'Penguen', 'Serçe'], answer: 2 },
  { type: 'multiple', question: 'Türkiye kaç coğrafi bölgeden oluşur?', options: ['5', '6', '7', '8'], answer: 2 },
  { type: 'multiple', question: '10 sayısının küpü kaçtır?', options: ['100', '1000', '110', '10'], answer: 1 },
  { type: 'multiple', question: 'Hangi renk üç ana renkten biridir?', options: ['Mor', 'Yeşil', 'Sarı', 'Pembe'], answer: 2 },
  { type: 'multiple', question: 'İnternetin temeli olan ağ hangisidir?', options: ['LAN', 'ARPANET', 'WLAN', 'FİBER'], answer: 1 },
  { type: 'multiple', question: 'İnsan vücudundaki en uzun kemik hangisidir?', options: ['Kol', 'Omurga', 'Uyluk', 'Kaburga'], answer: 2 },
  { type: 'multiple', question: 'Hangisi bir programlama dili değildir?', options: ['Python', 'HTML', 'Java', 'Excel'], answer: 3 },
  { type: 'multiple', question: '"Antik Roma" nerede kurulmuştur?', options: ['İspanya', 'Fransa', 'İtalya', 'Yunanistan'], answer: 2 },
  { type: 'multiple', question: 'Dünya\'nın tek doğal uydusu nedir?', options: ['Mars', 'Jüpiter', 'Ay', 'Venüs'], answer: 2 },
  { type: 'multiple', question: 'En küçük çift pozitif sayı hangisidir?', options: ['1', '2', '0', '4'], answer: 1 },
  { 
    type: 'matching', 
    question: 'Aşağıdaki ülkeleri başkentleriyle eşleştirin:', 
    leftItems: ['Türkiye', 'Fransa', 'Japonya', 'Mısır', 'Brezilya'],
    rightItems: ['Ankara', 'Paris', 'Tokyo', 'Kahire', 'Brasília'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki gezegenleri özellikleriyle eşleştirin:', 
    leftItems: ['Mars', 'Satürn', 'Venüs', 'Jüpiter', 'Merkür'],
    rightItems: ['Kırmızı gezegen', 'Halkalı gezegen', 'En sıcak gezegen', 'En büyük gezegen', 'Güneşe en yakın'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki matematik işlemlerini sonuçlarıyla eşleştirin:', 
    leftItems: ['8 x 7', '15 + 25', '100 ÷ 4', '12²', '5³'],
    rightItems: ['56', '40', '25', '144', '125'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki hayvanları yaşam alanlarıyla eşleştirin:', 
    leftItems: ['Balina', 'Kartal', 'Timsah', 'Penguen', 'Kanguru'],
    rightItems: ['Okyanus', 'Gökyüzü', 'Nehir', 'Kutuplar', 'Avustralya'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki renkleri duygularla eşleştirin:', 
    leftItems: ['Kırmızı', 'Mavi', 'Yeşil', 'Sarı', 'Mor'],
    rightItems: ['Öfke', 'Sakinlik', 'Doğa', 'Mutluluk', 'Asalet'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki bilim insanlarını buluşlarıyla eşleştirin:', 
    leftItems: ['Einstein', 'Newton', 'Tesla', 'Galileo', 'Darwin'],
    rightItems: ['Görelilik', 'Yerçekimi', 'Alternatif akım', 'Teleskop', 'Evrim teorisi'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki elementleri sembolleriyle eşleştirin:', 
    leftItems: ['Oksijen', 'Karbon', 'Hidrojen', 'Azot', 'Demir'],
    rightItems: ['O', 'C', 'H', 'N', 'Fe'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki sporları kategorileriyle eşleştirin:', 
    leftItems: ['Futbol', 'Yüzme', 'Satranç', 'Basketbol', 'Koşu'],
    rightItems: ['Takım sporu', 'Su sporu', 'Zeka sporu', 'Takım sporu', 'Atletizm'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki meslekleri araçlarıyla eşleştirin:', 
    leftItems: ['Doktor', 'Öğretmen', 'Mimar', 'Aşçı', 'Müzisyen'],
    rightItems: ['Steteskop', 'Tebeşir', 'Çizim tahtası', 'Tencere', 'Enstrüman'],
    answer: [0, 1, 2, 3, 4]
  },
  { 
    type: 'matching', 
    question: 'Aşağıdaki tarih olaylarını yıllarıyla eşleştirin:', 
    leftItems: ['İstanbul\'un fethi', 'Cumhuriyetin ilanı', 'II. Dünya Savaşı', 'Atatürk\'ün doğumu', 'Türkiye\'nin kuruluşu'],
    rightItems: ['1453', '1923', '1939', '1881', '1923'],
    answer: [0, 1, 2, 3, 1]
  }
]; 
